export enum MESSAGE_TYPE {
    THING_PROPERTY_REPORT = 'THING_PROPERTY_REPORT',
}

export enum MESSAGE_SINK_TYPE {
    KAFKA = 'KAFKA',
}

export enum MESSAGE_SOURCE_TOPICS {
    THING_PROPERTY_REPORT = 'THING_PROPERTY_REPORT',
}
