export enum ALARM_TRIGGER_MODE {
    CONTINUOUS = 'CONTINUOUS',
    SINGLE = 'SINGLE',
}

export enum ALARM_STATUS {
    UN_PROCESSED = 'UN_PROCESSED',
    MISREPORT = 'MISREPORT',
    PROCESSED = 'PROCESSED',
}
